[[headers]]
  for = "/*.m3u8"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Content-Type = "application/vnd.apple.mpegurl"
  Cache-Control = "no-cache"

[[headers]]
  for = "/*.ts"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Content-Type = "video/mp2t"
